### ISSUE TITLE
check changes in the config file instead of the temporary config file.

### ISSUE THREAD

**Issue by HanzzM** [ihrwein/puppet-syslog_ng#12]
The module don't enforces the desired state from the config file syslog-ng.conf.
I can freely change the config file on my local node.

**Comment by faxm0dem** [comment]
I think there is a misunderstanding on this issue. @HanzzM was referring to the fact that it is possible to modify the deployed `syslog-ng.conf` file, and not the temporary one. Please repoen this issue, and I'll cook a patch ASAP

**Comment by ihrwein** [comment]
Thanks, I reopened it!

**Comment by faxm0dem** [comment]
yeah so the problem is:
```Puppet
  file {$config_file:
    ensure => present,
    path   => $config_file,
    require => Concat[$tmp_config_file]
  }
```
when puppet doesn't manage a file resource's content, there's no way to notify other resources when it changes (change requires content management).
So IMHO there's no sane way to solve this with the current implementation using `$tmp_config_file`.
IMHO the only sane way to solve this is through #23

**Comment by ihrwein** [comment]
I checked @faxm0dem 's suggestion and it's supported above Puppet 3.5.0. 

Fabien, do you know which Puppet version's are the most widespreadly used nowadays? 

@HanzzM what Puppet version are you using?

**Comment by HanzzM** [comment]
sudo /opt/puppet/bin/puppet --version
3.6.2 (Puppet Enterprise 3.3.2)

**Comment by HanzzM** [comment]
Sorry, I leave this chat.
I'm no longer a user of this module.
